TaskWork-4.5.1
sulfidate/meet pull request #7
Opened 2022-04-03 12:51 UTC by sulfidate

2022-04-05 19:42 UTC, stratospherique requested changes

2022-04-05 19:42 UTC, stratospherique commented on src/features/filterEventsByCity.test.js
> +      }
For these tests, you need to define a variable that contains a filtered version of `mockData`. It contains the events that have 'berlin' in their location string. And the expect instruction would become like this:
`expect(AppWrapper.find('.event')).toHaveLength(filteredEvents.length)`

- The then block serves the same purpose of the `and` block. They could be merged into a single then block.

2022-04-05 19:42 UTC, stratospherique commented on src/features/specifyNumberOfEvents.feature
> +            And the number of events will specified
The feature is supposed to test the effect of changing the number of event input on the **number of displayed events**(not on the input itself). That require changes in the associated test file.

2022-04-07 09:59 UTC, sulfidate commented on src/features/filterEventsByCity.test.js
> +      }
OK Done :)

2022-04-07 14:05 UTC, sulfidate commented on src/features/filterEventsByCity.test.js
> +      }
Done :)

2022-04-07 17:37 UTC, stratospherique commented on src/features/specifyNumberOfEvents.feature
> +            And the number of events will specified
The file is still unchanged

2022-04-12 19:16 UTC, stratospherique commented on src/features/specifyNumberOfEvents.feature
> +            And the number of events will specified
yes, both files should be refactored.

2022-04-13 14:47 UTC, sulfidate commented on src/features/specifyNumberOfEvents.feature
> +            And the number of events will specified
ok, Done

2022-04-14 12:17 UTC, merged